language: python
python:
  - "3.7"
  
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libxml2-dev
  
install:
  - pip install --user pandas
  - pip install --user matplotlib
  - pip install --user os
  - pip install --user seaborn
  - pip install --user numpy
  - pip install --user sklearn

script:
  - python3 Heatmap.py
